variable "namespace" {}
variable "ami" {}
variable "vpc_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "cidr_block" {}
variable "number_of_instances" {}
variable "allow_bastion_security_group" {}
variable "environment" {}
variable "environment_subdomain" {}
variable "swarm_domain_name" {}
variable "consul_domain_name" {}
variable "consul_security_group" {}
variable "swarm_manager_security_group" {}
variable "logstash_security_group" {}
variable "public_hosted_zone_id" {}
