module "vpc" {
    source = "../../modules/vpc"
    name = "${var.environment_name}"
    cidr = "10.1.0.0/16"
    private_subnets = "10.1.0.0/21,10.1.64.0/21,10.1.128.0/21"
    public_subnets = "10.1.32.0/22,10.1.96.0/22,10.1.160.0/22"
    availability_zones = "eu-west-1a,eu-west-1b,eu-west-1c"
    private_hosted_zone_id = "${var.private_hosted_zone_id}"
}

module "public-subdomain" {
    source = "../../modules/public-subdomain"
    parent_hosted_zone_id = "Z3820KW3201KHJ"
    subdomain = "${var.environment_subdomain}"
}

module "bastion-host" {
    namespace = "${var.environment_name}"
    source = "../../modules/bastion-host"
    ami = "${var.bastion_host_ami}"
    vpc_id = "${module.vpc.vpc_id}"
    allowed_ip_addresses = "${var.allowed_ip_address}"
    instance_type = "t2.micro"
    key_name = "${var.bastion_key_name}"
    public_subnets = "${module.vpc.public_subnets}"
    bastion_host_domain_name = "vquex.${var.environment_subdomain}"
    cidr_block = "${module.vpc.cidr_block}"
    public_hosted_zone_id = "${module.public-subdomain.subdomain_hosted_zone}"
}

module "consul-cluster" {
    namespace = "${var.environment_name}"
    source = "../../modules/consul-cluster"
    ami = "${var.docker_base_ami}"
    vpc_id = "${module.vpc.vpc_id}"
    instance_type = "t2.micro"
    key_name = "${var.instance_key_name}"
    private_subnets = "${module.vpc.private_subnets}"
    cidr_block = "${module.vpc.cidr_block}"
    no_of_nodes_in_cluster = "${var.consul_cluster_count}"
    allow_bastion_security_group = "${module.bastion-host.allow_bastion_security_group_id}"
    private_hosted_domain_name = "${var.private_hosted_zone}"
    private_hosted_zone_id = "${var.private_hosted_zone_id}"
}

module "swarm-manager-cluster" {
    namespace = "${var.environment_name}"
    source = "../../modules/swarm-manager-cluster"
    ami = "${var.docker_base_ami}"
    vpc_id = "${module.vpc.vpc_id}"
    instance_type = "t2.micro"
    key_name = "${var.instance_key_name}"
    private_subnets = "${module.vpc.private_subnets}"
    cidr_block = "${module.vpc.cidr_block}"
    no_of_nodes_in_cluster = "${var.swarm_cluster_count}"
    allow_bastion_security_group = "${module.bastion-host.allow_bastion_security_group_id}"
    private_hosted_domain_name = "${var.private_hosted_zone}"
    private_hosted_zone_id = "${var.private_hosted_zone_id}"
    consul_domain_name = "consul.${var.private_hosted_zone}"
    consul_security_group = "${module.consul-cluster.consul_security_group}"
    overlay_network_name = "${var.environment_name}"
    core_services_vpc_cidr = "${var.core_services_vpc_cidr}"
}

module "swarm-node-cluster" {
    namespace = "${var.environment_name}"
    source = "../../modules/swarm-node-cluster"
    ami = "${var.docker_base_ami}"
    vpc_id = "${module.vpc.vpc_id}"
    instance_type = "t2.medium"
    key_name = "${var.instance_key_name}"
    public_subnets = "${module.vpc.public_subnets}"
    private_subnets = "${module.vpc.private_subnets}"
    cidr_block = "${module.vpc.cidr_block}"
    number_of_instances = "${var.default_node_cluster_size}"
    allow_bastion_security_group = "${module.bastion-host.allow_bastion_security_group_id}"
    environment_subdomain = "${var.environment_subdomain}"
    environment = "${var.environment_name}"
    consul_domain_name = "consul.${var.private_hosted_zone}"
    swarm_domain_name = "swarm.${var.private_hosted_zone}"
    consul_security_group = "${module.consul-cluster.consul_security_group}"
    swarm_manager_security_group = "${module.swarm-manager-cluster.swarm_manager_security_group}"
    public_hosted_zone_id = "${module.public-subdomain.subdomain_hosted_zone}"
    logstash_security_group = "${module.logstash-cluster.logstash_security_group}"
}

module "elasticsearch-cluster" {
    namespace = "${var.environment_name}"
    source = "../../modules/elastic-search"
    ami = "${var.docker_base_ami}"
    vpc_id = "${module.vpc.vpc_id}"
    instance_type = "t2.medium"
    key_name = "${var.instance_key_name}"
    private_subnets = "${module.vpc.private_subnets}"
    cidr_block = "${module.vpc.cidr_block}"
    no_of_nodes_in_cluster = "${var.elastic_search_cluster_count}"
    allow_bastion_security_group = "${module.bastion-host.allow_bastion_security_group_id}"
    private_hosted_domain_name = "${var.private_hosted_zone}"
    private_hosted_zone_id = "${var.private_hosted_zone_id}"
    consul_domain_name = "consul.${var.private_hosted_zone}"
    consul_security_group = "${module.consul-cluster.consul_security_group}"
}

module "logstash-cluster" {
    namespace = "${var.environment_name}"
    source = "../../modules/logstash"
    ami = "${var.docker_base_ami}"
    vpc_id = "${module.vpc.vpc_id}"
    instance_type = "t2.medium"
    key_name = "${var.instance_key_name}"
    private_subnets = "${module.vpc.private_subnets}"
    cidr_block = "${module.vpc.cidr_block}"
    no_of_nodes_in_cluster = "${var.logstash_cluster_count}"
    allow_bastion_security_group = "${module.bastion-host.allow_bastion_security_group_id}"
    private_hosted_domain_name = "${var.private_hosted_zone}"
    private_hosted_zone_id = "${var.private_hosted_zone_id}"
    consul_domain_name = "consul.${var.private_hosted_zone}"
    consul_security_group = "${module.consul-cluster.consul_security_group}"
    elasticsearch_domain_name = "elasticsearch.${var.private_hosted_zone}"
    elasticsearch_security_group = "${module.elasticsearch-cluster.elasticsearch_security_group}"
}

module "kibana-cluster" {
    namespace = "${var.environment_name}"
    source = "../../modules/kibana"
    ami = "${var.docker_base_ami}"
    vpc_id = "${module.vpc.vpc_id}"
    instance_type = "t2.medium"
    key_name = "${var.instance_key_name}"
    private_subnets = "${module.vpc.private_subnets}"
    cidr_block = "${module.vpc.cidr_block}"
    no_of_nodes_in_cluster = "${var.kibana_cluster_count}"
    allow_bastion_security_group = "${module.bastion-host.allow_bastion_security_group_id}"
    private_hosted_domain_name = "${var.private_hosted_zone}"
    private_hosted_zone_id = "${var.private_hosted_zone_id}"
    consul_domain_name = "consul.${var.private_hosted_zone}"
    consul_security_group = "${module.consul-cluster.consul_security_group}"
    elasticsearch_domain_name = "elasticsearch.${var.private_hosted_zone}"
    elasticsearch_security_group = "${module.elasticsearch-cluster.elasticsearch_security_group}"
}
