variable "namespace" {}
variable "name" {}
variable "vpc_id" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "ingress_cidr_blocks" {}
variable "key_name" {}
variable "ami" {}
variable "instance_type" {}
variable "domain_name" {}
variable "allow_bastion_security_group" {}
variable "private_hosted_zone_id" {}